### ISSUE TITLE
Add support for Home Assistant Energy integration

### ISSUE THREAD

**Issue by PimDoos** [Emilv2/huawei_solar#24]
To support the new [Home Assistant Energy](https://www.home-assistant.io/docs/energy) integration and history statistics, huawei_solar should: 
* Include a `state_class` of `measurement` for the main sensor
* Define a seperate sensor for daily_yield, which has a `last_reset` attribute to ensure it's tracked properly
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by Techwolf12** [comment]
I did notice you don't need the daily_yield, a total_yield is also fine as long as it has a last_reset attribute on it. 
For example, my energy meter has a last_rest on epoch 0 (01-01-1970) and that works fine with the energy integration.

But support for this awesome new feature would be amazing!

**Comment by Emilv2** [comment]
Doesn't look to complicated, I'll take a look at it.

**Comment by inigoml** [comment]
+1. Would be great in order to have long term stats.

**Comment by triplecillas** [comment]
> Doesn't look to complicated, I'll take a look at it.

Thanks in advance for your time and effort.

**Comment by matheusvsv** [comment]
If anyone want to start using the new energy integration you can create a compatible sensor in your configuration.yaml
I created this sensor from the daily_yield attribute:

```
template:
  - sensor:
      - name: "Solar Daily Yield"
        state: >
          {{ state_attr('sensor.sun2000l_5ktl', 'daily_yield') | float }}
        device_class: 'energy'
        unit_of_measurement: 'kWh'
        state_class: "measurement"
        attributes:
          last_reset: "{{ now().replace(hour=0,minute=0,second=0,microsecond=0) }}"
```

If your huawei inverter doesn't have a working daily_yield attribute you can use the total_yield attribute but the last_reset on the code above need to be set to epoch time
