### ISSUE TITLE
dont work 

### ISSUE THREAD

**Issue by agmuz** [Emilv2/huawei_solar#47]
error dont work 439c23c

**Comment by Emilv2** [comment]
Please provide a bit more context. What doesn't work? Can you show any logs?

**Comment by lolopepes** [comment]
For me too not working from last updates

**Comment by agmuz** [comment]
version 439c23c no integration visible, no attributes, I restored a copy of 2485325 work ok, I don't have a log :(

**Comment by Emilv2** [comment]
Configuration -> logs shows nothing related to huawei_solar?

**Comment by agmuz** [comment]
2021-11-11 20:25:37 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by Emilv2** [comment]
Nothing else?

What if you set the logger to debug for the huawei_solar component?

```
logger:
  default: error
    logs:
      custom_components.huawei_solar: debug
```

**Comment by agmuz** [comment]
I cannot use this entry, the configuration file does not accept it

**Comment by Emilv2** [comment]
Sorry, I made a small mistake in the formatting, this should work:
```
logger:
  default: info
  logs:
    custom_components.huawei_solar: debug
```
