### ISSUE TITLE
Not capable of connecting

### ISSUE THREAD

**Issue by Rvh91** [Emilv2/huawei_solar#82]
Hi, 

First of all thank you for making this integration. Would love to have the inverter integrated in HA.
Not sure if this is the right place to reach out, but I cannot seem to setup this integration. 

My setup is as following:
Huawei SUN2000-8KTL-M1, firmware: SPC140
     Modbus-TCP → Enable(unrestricted)
     Parallel system communication parameter setting → Parallel communication mode" to RS485
Huawei SdongleA-05, firmware: SPC124, 
     connected via UTP cable to my home network with IP: 192.168.178.52/24.

I've added the following in my configuration:
```
sensor:
  - platform: huawei_solar   
    host: '192.168.178.52'
    optimizers: false
    battery: false
    slave: 1
    port: 6607
```

I'm using the IP of the Sdongle for the host. But no sensors are showing up. I also don't see anything in the logs in relation to this integration. I'm not sure how to proceed in debugging. Could someone provide me some direction?
